### ISSUE TITLE
TypeScript报错：循环引用其自身 App.tsx(51)

### ISSUE THREAD

**Issue by Hokori23** [techtrainingcamp-frontend-7/BD7#13]
> 属性“demo”的类型在已映射的类型“ExtractRematchDispatchersFromModels<{ [x: string]: ...; demo: { name?: string | undefined; state: DemoState; selectors: ModelSelectorsConfig<RootModel, DemoState>; reducers: { ...; }; baseReducer: Reducer<...>; effects: (dispatch: RematchDispatch<...>) => { ...; }; }; ... 6 more ...; common: { ...; }; }>”中循环引用其自身。ts(2615)

![image](https://user-images.githubusercontent.com/46038399/112844902-d112bf80-90d6-11eb-91cb-0b642139cb90.png)

**Comment by Hokori23** [comment]
发现是TypeScript4.2.3才会有这个报错
原先项目TypeScript版本为4.0.2

**Comment by upupming** [comment]
降低版本没有意义，这个报错不会影响当前的编译过程，只是一个提醒。而且这个循环引用实际上对打包工具来说可以正确处理。

还是建议用hook，参考home页面，简洁简单，connect太臃肿了

**Comment by Hokori23** [comment]
> 降低版本没有意义，这个报错不会影响当前的编译过程，只是一个提醒。而且这个循环引用实际上对打包工具来说可以正确处理。
> 
> 还是建议用hook，参考home页面，简洁简单，connect太臃肿了

戳实是hook舒服。。
